### ISSUE TITLE
Title: After import project into Eclipse, can't access assign.jsp

### ISSUE THREAD

**Issue by Hurambar** [liuzongdong/teaching-assignment-system#2]
HTTP Status 500 – Internal Server Error

**Comment by Hurambar** [comment]
Type: Exception Report
Message: Unable to compile class for JSP
Description: The server encountered an unexpected condition that prevented it from fulfilling the request.
Exception
`org.apache.jasper.JasperException: Unable to compile class for JSP
	org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:617)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:368)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)`

**Comment by liuzongdong** [comment]
Thanks for your testing, bug fixed, please fork/clone the latest version.
